default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  hostname: localhost
  database: myfinance_dev
  username: myfinance_dev_user
  password: dev

test:
  <<: *default
  hostname: localhost
  database: myfinance_test
  username: myfinance_dev_user
  password: dev

production:
  <<: *default
  hostname: localhost
  database: myfinance_prod
  username: myfinance_prod_user
  password: Password1@
